version: '3.8'
services:
  api:
    container_name: 'wehost_be_${NODE_ENV}'
    image: 'wehost_be_${NODE_ENV}'
    environment:
      - NODE_ENV:${NODE_ENV}
    command: yarn
    build:
      context: .
      dockerfile: Dockerfile
      target: '${NODE_ENV}'
    env_file:
      - .env
    entrypoint:
      - yarn
      - run
      - 'start:${NODE_ENV}'

    ports:
      - ${PORT}:${PORT}
    networks:
      - nesjs-network
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    container_name: wehost_postgres
    image: postgres:14.3-alpine
    networks:
      - nesjs-network
    environment:
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_DB:${POSTGRES_DB}
      - PG_DATA:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./pgdata/data:/var/lib/postgresql/data

networks:
  nesjs-network:
